### ISSUE TITLE
path组件的d属性设置成M 5 2,h 154,q 3 0 3 3,v 164,q 0 3 -3 3,h -154,q -3 0 -3 -3,v -164,q 0 -3 3 -3无效

### ISSUE THREAD

**Issue by xiaolieask** [react-native-oh-library/react-native-harmony-svg#185]
使用Path组件，将d属性设置成M 5 2,h 154,q 3 0 3 3,v 164,q 0 3 -3 3,h -154,q -3 0 -3 -3,v -164,q 0 -3 3 -3
随意设置fill颜色
浏览器代码：
```
<svg>
     <path d="M 5 2,h 154,q 3 0 3 3,v 164,q 0 3 -3 3,h -154,q -3 0 -3 -3,v -164,q 0 -3 3 -3" fill="rgba(3,102,214,0.2)"></path>
</svg>
```
效果：
![image](https://github.com/react-native-oh-library/react-native-harmony-svg/assets/26913643/b1d6ba30-0766-4f23-92d4-18293daeb951)
真机代码片段：
```
<Svg>
       <Path d="M 5 2,h 154,q 3 0 3 3,v 164,q 0 3 -3 3,h -154,q -3 0 -3 -3,v -164,q 0 -3 3 -3" fill="rgba(3,102,214,0.2)"></Path>
</Svg>
```
效果：
白屏
更换其他d值有效果出现

**Comment by Louis-C7** [comment]
M 5 2 h 154 q 3 0 3 3v 164 q 0 3 -3 3 h -154 q -3 0 -3 -3v -164 q 0 -3 3 -3
