### ISSUE TITLE
SvgUri 无法引用本地文件

### ISSUE THREAD

**Issue by JCdahuzi** [react-native-oh-library/react-native-harmony-svg#254]
### 描述 / Description

# Demo
```js
import React, { Component } from 'react';
import { View } from 'react-native';
import { SvgUri } from 'react-native-svg';

export default class SvgNativeMethods extends Component {
  render() {
    return (
      <View style={{ margin: 50 }}>
        <SvgUri
          width="150"
          height="70"
          uri="file://assets/svgdemocases_components_debian.svg"
        />
      </View>
    );
  }
}
```
不能显示svg文件的图像内容

### 复现步骤 / Steps to reproduce

1. 存储svg文件
2. 使用SvgUri uri=“file://xxx.svg” 去引用 svg 文件
3. 运行代码去观察现象

### 库版本 / Library version

15.0.0-0.5.2

### React Native OpenHarmony version

0.72.27

### 构建类型 / Build type

Debug app & dev bundle

### 设备 / Device

Real device

### 已悉知 / Acknowledgements

Yes

**Comment by Louis-C7** [comment]
该问题的根因为RN框架的fetch()接口有问题，待RN框架修复

**Comment by Louis-C7** [comment]
在react-native-harmony@0.72.34中已修复fetch接口不支持本地资源URL的问题，该组件恢复正常。
