### ISSUE TITLE
在hsp里使用react-native-harmony-svg，Image无法加载图片

### ISSUE THREAD

**Issue by wufeiqaq** [react-native-oh-library/react-native-harmony-svg#265]
### 描述 / Description

在entry 中集成RN,link link react-native-harmony-svg,在RN端使用 svg  image,图片能正常显示；
在一个hsp中使用 RN link react-native-harmony-svg, svg image显示空白
发现是只能加载resources下的文件，而且是要在 uiAbilityContext.resourceManeger下，无法加载RN bundle 同级目录下assets/下的资源

### 复现步骤 / Steps to reproduce

1、在一个hsp里集成RN，并且在link react-native-harmony-svg；
2、在RN 端使用svg的 Image 

```
import { Image as SvgImage, Svg,Defs,ClipPath,Circle,Rect} from 'react-native-svg';
<Svg height="100" width="100">
        <SvgImage
          x="5%"
          y="5%"
          width="50%"
          height="90%"
          href={require('../images/test.png')}
        />
      </Svg>
```
3、图片无法显示出来；

### 库版本 / Library version

15.0.0-0.5.4

### React Native OpenHarmony version

0.72.27

### 构建类型 / Build type

Debug app & dev bundle

### 设备 / Device

Real device

### 设备版本 / Device model

mate 60 5.0.0.25

### 已悉知 / Acknowledgements

Yes

**Comment by Louis-C7** [comment]
这种场景下，react-native的Image组件可以正常读取到本地资源么？

**Comment by Louis-C7** [comment]
> ### 描述 / Description
> 在entry 中集成RN,link link react-native-harmony-svg,在RN端使用 svg image,图片能正常显示； 在一个hsp中使用 RN link react-native-harmony-svg, svg image显示空白 发现是只能加载resources下的文件，而且是要在 uiAbilityContext.resourceManeger下，无法加载RN bundle 同级目录下assets/下的资源
> 
> ### 复现步骤 / Steps to reproduce
> 1、在一个hsp里集成RN，并且在link react-native-harmony-svg； 2、在RN 端使用svg的 Image
> 
> ```
> import { Image as SvgImage, Svg,Defs,ClipPath,Circle,Rect} from 'react-native-svg';
> <Svg height="100" width="100">
>         <SvgImage
>           x="5%"
>           y="5%"
>           width="50%"
>           height="90%"
>           href={require('../images/test.png')}
>         />
>       </Svg>
> ```
> 
> 3、图片无法显示出来；
> 
> ### 库版本 / Library version
> 15.0.0-0.5.4
> 
> ### React Native OpenHarmony version
> 0.72.27
> 
> ### 构建类型 / Build type
> Debug app & dev bundle
> 
> ### 设备 / Device
> Real device
> 
> ### 设备版本 / Device model
> mate 60 5.0.0.25
> 
> ### 已悉知 / Acknowledgements
> Yes

这种场景下，react-native的Image组件可以正常读取到本地资源么？

**Comment by wufeiqaq** [comment]
在RN的package.json 的scripts 添加"react-native bundle-harmony --dev false --entry-file ./index.js  --bundle-output ./harmony/entry/src/main/resource/rawfile/index.bundle --assets-dest ./harmony/entry/src/main/resource/rawfile"  打包命令，打包出来的bundle 和资源，Image 是可以显示的。  使用"react-native bundle-harmony --dev" 打包的是不能显示的

我看RN源码中RNInstancesCoordinator构造函数中
```
new RNInstanceRegistry(
      this.rawLogger,
      napiBridge,
      this.devToolsController,
      (rnInstance) => RNOHContext.fromCoreContext(this.rnohCoreContext, rnInstance),
      httpClientProvider,
      options?.defaultHttpClient,
      this.uiAbilityContext.resourceManager
    )
```
使用的是uiAbilityContext.resourceManager
最后在RNInstanceImpl的initialize中传入native的就是这个uiAbilityContext.resourceManager
```
this.napiBridge.createReactNativeInstance(
      this.id,
      this.turboModuleProvider,
      this.frameNodeFactoryRef,
      (mutations) => {
        try {
          this.descriptorRegistry.applyMutations(mutations)
        } catch (err) {
          if (typeof err === "string") {
            this.logger.error(err)
          } else if (err instanceof Error) {
            this.logger.error(err.message)
            if (err.stack) {
              this.logger.error(err.stack)
            }
          } else {
            this.logger.error("Unexpected error when applying mutations")
          }
        }
      },
      (tag, commandName, args) => {
        this.componentCommandHub.dispatchCommand(tag, commandName, args)
      },
      (type, payload) => {
        this.onCppMessage(type, payload)
      },
      this.shouldEnableDebugger,
      this.shouldEnableBackgroundExecutor,
      cppFeatureFlags,
      this.resourceManager,
      this.arkTsComponentNames,
      fontOptions
    )
```
RNSVGImageComponentInstance.cpp 代码中拿到的就是这个resourceManager吧
```
if (rnInstance != nullptr) {
            auto nativeResourceManager = rnInstance->getNativeResourceManager();
            svgImage->setNativeResourceManager(nativeResourceManager);
        }
```
SvgImage.cpp 是通过nativeResourceManager 获取文件的
```
 auto rawFile = OH_ResourceManager_OpenRawFile(mgr_, file.c_str());
```
resourceManager 是不是不能拿到getContext().filesDir 或者getContext().cacheDir 下的文件
只有将资源放一份在entry的resource/rawfile 下svgImage才能显示出来

**Comment by Louis-C7** [comment]
> 在RN的package.json 的scripts 添加"react-native bundle-harmony --dev false --entry-file ./index.js --bundle-output ./harmony/entry/src/main/resource/rawfile/index.bundle --assets-dest ./harmony/entry/src/main/resource/rawfile" 打包命令，打包出来的bundle 和资源，Image 是可以显示的。 使用"react-native bundle-harmony --dev" 打包的是不能显示的
> 
> 我看RN源码中RNInstancesCoordinator构造函数中
> 
> ```
> new RNInstanceRegistry(
>       this.rawLogger,
>       napiBridge,
>       this.devToolsController,
>       (rnInstance) => RNOHContext.fromCoreContext(this.rnohCoreContext, rnInstance),
>       httpClientProvider,
>       options?.defaultHttpClient,
>       this.uiAbilityContext.resourceManager
>     )
> ```
> 
> 使用的是uiAbilityContext.resourceManager 最后在RNInstanceImpl的initialize中传入native的就是这个uiAbilityContext.resourceManager
> 
> ```
> this.napiBridge.createReactNativeInstance(
>       this.id,
>       this.turboModuleProvider,
>       this.frameNodeFactoryRef,
>       (mutations) => {
>         try {
>           this.descriptorRegistry.applyMutations(mutations)
>         } catch (err) {
>           if (typeof err === "string") {
>             this.logger.error(err)
>           } else if (err instanceof Error) {
>             this.logger.error(err.message)
>             if (err.stack) {
>               this.logger.error(err.stack)
>             }
>           } else {
>             this.logger.error("Unexpected error when applying mutations")
>           }
>         }
>       },
>       (tag, commandName, args) => {
>         this.componentCommandHub.dispatchCommand(tag, commandName, args)
>       },
>       (type, payload) => {
>         this.onCppMessage(type, payload)
>       },
>       this.shouldEnableDebugger,
>       this.shouldEnableBackgroundExecutor,
>       cppFeatureFlags,
>       this.resourceManager,
>       this.arkTsComponentNames,
>       fontOptions
>     )
> ```
> 
> RNSVGImageComponentInstance.cpp 代码中拿到的就是这个resourceManager吧
> 
> ```
> if (rnInstance != nullptr) {
>             auto nativeResourceManager = rnInstance->getNativeResourceManager();
>             svgImage->setNativeResourceManager(nativeResourceManager);
>         }
> ```
> 
> SvgImage.cpp 是通过nativeResourceManager 获取文件的
> 
> ```
>  auto rawFile = OH_ResourceManager_OpenRawFile(mgr_, file.c_str());
> ```
> 
> resourceManager 是不是不能拿到getContext().filesDir 或者getContext().cacheDir 下的文件 只有将资源放一份在entry的resource/rawfile 下svgImage才能显示出来

请问下，目前是希望把RN bundle和资源图片放到什么路径下？资源的路径是由RN框架统一处理，然后传递到三方库，默认是harmony/entry/src/main/resources/rawfile下的rawfile路径，而且resourceManager 貌似只能读rawfile，是不能拿到getContext().filesDir 或者getContext().cacheDir 下的文件的

**Comment by wufeiqaq** [comment]
是沙箱路径，我是将打包后的bundle和资源放在沙盒目录下的，目录结构如图：
![WX](https://github.com/user-attachments/assets/e393be92-5f7f-4c8e-8471-da08378f7294)
 我想让 Svg Image 能加载到test/images 下的资源

**Comment by Louis-C7** [comment]
> 是沙箱路径，我是将打包后的bundle和资源放在沙盒目录下的，目录结构如图： ![WX](https://private-user-images.githubusercontent.com/161403503/353688356-e393be92-5f7f-4c8e-8471-da08378f7294.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzOTgzOTUsIm5iZiI6MTcyMjM5ODA5NSwicGF0aCI6Ii8xNjE0MDM1MDMvMzUzNjg4MzU2LWUzOTNiZTkyLTVmN2YtNGM4ZS04NDcxLWRhMDgzNzhmNzI5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQwMzU0NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzM0ZTczOGFmMjdiNTBlMmVjOGZjNTU1Y2QzZTljNDNmNzI0NTgzZWE4ZmY1MmY0N2ZjOWNmOGU3Y2Y4OTM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.grNdMuSoFXabhM6wtbzvVvoKKheMV8fD3i68vv2hvP0) 我想让 Svg Image 能加载到test/images 下的资源

了解。我们会尝试下满足这种场景，暂时请先放到rawfile下

**Comment by mashuai65** [comment]
修改image的href属性，需要确保传递的文件路径存在
href = "/data/storage/el2/base/haps/entry/files/test/images/test.png", 不用require
