### ISSUE TITLE
Svg中组件的fill不能设置透明色，导致他下面的组件展示不出来

### ISSUE THREAD

**Issue by hf529270451** [react-native-oh-library/react-native-harmony-svg#269]
### 描述 / Description

我的Svg叠在另一个组件上面，需要通过fill设置透明 显示下面的内容，而且ios，android默认fill就是透明的，但是我设置了fill没反应。

### 复现步骤 / Steps to reproduce

<Svg
        style={{
          width:
            radius * 2 +
            (Platform.OS === 'ios' ? strokeWidth * 2 : strokeWidth * scale2),
          height:
            radius * 2 +
            (Platform.OS === 'ios' ? strokeWidth * 2 : strokeWidth * scale2),
        }}>
        <Circle
          cx={Platform.OS == 'ios' ? cx : (cx * scale1) / scale2}
          cy={Platform.OS == 'ios' ? cy : (cy * scale1) / scale2}
          r={radius}
          strokeWidth={strokeWidth}
          stroke={bgColor}
// 这行代码不生效
          fill={'#00000000'}
        />
       
      </Svg>

### 库版本 / Library version

15.0.0-0.5.4

### React Native OpenHarmony version

5.0.0.302

### 构建类型 / Build type

None

### 设备 / Device

None

### 已悉知 / Acknowledgements

Yes

**Comment by cmdssd** [comment]
> ### 描述 / Description
> 我的Svg叠在另一个组件上面，需要通过fill设置透明 显示下面的内容，而且ios，android默认fill就是透明的，但是我设置了fill没反应。
> 
> ### 复现步骤 / Steps to reproduce
> <Svg style={{ width: radius * 2 + (Platform.OS === 'ios' ? strokeWidth * 2 : strokeWidth * scale2), height: radius * 2 + (Platform.OS === 'ios' ? strokeWidth * 2 : strokeWidth * scale2), }}> <Circle cx={Platform.OS == 'ios' ? cx : (cx * scale1) / scale2} cy={Platform.OS == 'ios' ? cy : (cy * scale1) / scale2} r={radius} strokeWidth={strokeWidth} stroke={bgColor} // 这行代码不生效 fill={'#00000000'} />
> 
> ```
>   </Svg>
> ```
> 
> ### 库版本 / Library version
> 15.0.0-0.5.4
> 
> ### React Native OpenHarmony version
> 5.0.0.302
> 
> ### 构建类型 / Build type
> None
> 
> ### 设备 / Device
> None
> 
> ### 设备版本 / Device model
> _No response_
> 
> ### 已悉知 / Acknowledgements
> Yes

您好，我这边用您发的这个demo测试了一下，发现这个属性是能正常使用的.希望您能提供更多信息以供定位问题
具体demo与显示结果如下

``` js
export default function Issue244() {
  const radius = 50;
  const strokeWidth = 5;
  const bgColor = 'pink';
  const cx = 55;
  const cy = 55;
  const scale1 = 1;
  const scale2 = 1;
  return (
    <View style={{padding: 20, width: 150, height: 150}}>
      <View style={{position: 'absolute',height:'80',backgroundColor:'blue'}}>
          <Button title='ssdssssssss'></Button>
      </View>
      <Svg
        style={{
          width:
          radius * 2 +
          (Platform.OS === 'ios' ? strokeWidth * 2 : strokeWidth * scale2),
          height:
          radius * 2 +
          (Platform.OS === 'ios' ? strokeWidth * 2 : strokeWidth * scale2),
          }}>
          <Circle
          cx={Platform.OS == 'ios' ? cx : (cx * scale1) / scale2}
          cy={Platform.OS == 'ios' ? cy : (cy * scale1) / scale2}
          r={radius}
          strokeWidth={strokeWidth}
          stroke={bgColor}
          // 这行代码不生效
          fill={'#00000000'}
        />
      </Svg>
    </View>
  );
}
```

![IMG_1722654580_011](https://github.com/user-attachments/assets/346c5713-2af0-42ef-9b8f-6192c5db684e)

**Comment by hf529270451** [comment]
感谢 解决了
