### ISSUE TITLE
svg下嵌套react-native的Text组件不显示

### ISSUE THREAD

**Issue by xuxiaoqian1** [react-native-oh-library/react-native-harmony-svg#274]
### 描述 / Description

问题复现demo:
```
import { Text, View } from 'react-native';
import Svg from 'react-native-svg'

export default function (){
  return (
    <View style={{marginTop: 30}}>
       <Svg>
        <View>
          <Text>测试</Text>
        </View>
       </Svg>
    </View>
  );
};
```

### 库版本 / Library version

15.0.0-0.5.4

### React Native OpenHarmony version

0.72.28

### 构建类型 / Build type

Debug app & dev bundle

### 设备 / Device

Real device

### 设备版本 / Device model

Mate 60 pro(3.0.0.29)

### 已悉知 / Acknowledgements

Yes

**Comment by JCdahuzi** [comment]
暂不支持foreignObject

**Comment by Louis-C7** [comment]
和issue #256 重复，关闭
