### ISSUE TITLE
在沙箱路径中，bundle和资源路径同级的情况下，加载资源失败

### ISSUE THREAD

**Issue by mashuai65** [react-native-oh-library/react-native-harmony-svg#278]
### 描述 / Description

将bundle和资源推送到沙箱路径中，其中的资源加载失败，
比如在使用图片资源，期望加载出图片，但是显示是空白的
```
<Svg height="100" width="100">
        <SvgImage
          x="5%"
          y="5%"
          width="50%"
          height="90%"
          href={require('../images/test.png')}
        />
</Svg>
```

### 库版本 / Library version

15.0.0-0.5.6

### React Native OpenHarmony version

0.72.27

### 构建类型 / Build type

None

### 设备 / Device

None

### 已悉知 / Acknowledgements

Yes

**Comment by Louis-C7** [comment]
和#265重复，关闭
