### ISSUE TITLE
渐变尺寸异常，导致阴影重叠或间隙

### ISSUE THREAD

**Issue by mashuai65** [react-native-oh-library/react-native-harmony-svg#284]
### 描述 / Description

在使用三方库[阴影](https://github.com/SrBrahma/react-native-shadow-2)，依赖于svg的渐变功能，角落出现异常，出现阴影重叠或间隙现象。
![shadow_harmony](https://github.com/user-attachments/assets/4ed1a219-7227-4a01-ada0-30a70905aebb)
（此现象是在31的系统版本中现象，在36中没有间隙；在PC的36中显示正常，60中存在重叠，需要将阴影源码中corners的定位的distance后面-1后正常）
![20240819-182046(WeLinkPC)](https://github.com/user-attachments/assets/27f95fe4-e4b2-483e-8f6e-7c007f46152b)
（此现象是PC 36）

### 复现步骤 / Steps to reproduce

1. 下载shadow-2源码，放在tester/svgDemoCases/components目录， shadow为index.tsx重命名
2. 将下面文件命名为ShadowDemo.tsx
 ```
import {Text, View, StyleSheet, ScrollView} from 'react-native';
import {Shadow} from './shadow';

export default function ShadowDemo() {
  return (
    <ScrollView style={styles.wrap}>
      <Shadow distance={10} style={styles.shadow}>
        <Text style={styles.box}>shadow 10</Text>
      </Shadow>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  wrap: {
    backgroundColor: 'white',
    width: '200%',
    height: '100%',
    padding: 20,
  },
  shadow: {
    marginBottom: 150,
  },
  safe: {
    height: 100,
    margin: 20,
    backgroundColor: 'white',
  },
  text: {
    alignSelf: 'center',
    paddingVertical: 20,
  },
  title: {
    fontSize: 30,
    marginTop: 20,
  },
  box: {
    margin: 40,
    fontSize: 16,
  },
  sliderOne: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
});
```
4. 在index.tsx中添加
```
import ShadowDemo from './ShadowDemo';
export default {
...
ShadowDemo,
}

```

### 库版本 / Library version

15.0.0-0.5.6

### React Native OpenHarmony version

0.72.27

### 构建类型 / Build type

None

### 设备 / Device

Real device

### 设备版本 / Device model

Mate 60(5.0.0.36)

### 已悉知 / Acknowledgements

Yes

**Comment by Louis-C7** [comment]
系统问题导致，阴影库参考iOS补充精度丢失的部分位移
