### ISSUE TITLE
我的Image标签不显示图片，一片空白

### ISSUE THREAD

**Issue by owenlee66** [react-native-oh-library/react-native-harmony-svg#295]
# 显示不了图片
demo
    <SvgImage
          x={20}
          y={20}
          width={60}
          height={60}
          href={{uri: fileUrl(`${model}.png`)}}
        />
我这样显示不了图片，然后我改成require引用本地也显示不了，但是我react native的Image标签可以正常显示
导入的是react-native-oh-tpl-react-native-svg-15.0.0-0.5.7.tgz

**Comment by JCdahuzi** [comment]
请使用 Image。
import { Image as SvgImage } from 'react-native-svg' 
<SvgImage
          x="5%"
          y="5%"
          width="50%"
          height="90%"
          opacity="0.5"
          href={require('../assets/image.jpg')}
        />
